library(tidyverse)
setwd("~/Downloads")

#Obtain Data
dataset=read.csv("student-mat.csv")
dataset

#Cleaning Data
str(dataset)
unique(dataset$school)
dataset$school=as.factor(dataset$school)
unique(dataset$sex)
dataset$sex=as.factor(dataset$sex)
unique(dataset$address)
dataset$address=as.factor(dataset$address)
unique(dataset$famsize)
dataset$famsize=as.factor(dataset$famsize)
unique(dataset$Pstatus)
dataset$Pstatus=as.factor(dataset$Pstatus)
unique(dataset$guardian)
dataset$guardian=as.factor(dataset$guardian)
dataset$schoolsup=as.factor(dataset$schoolsup)
dataset$famsup=as.factor(dataset$famsup)
dataset$paid=as.factor(dataset$paid)
dataset$activities=as.factor(dataset$activities)
dataset$nursery=as.factor(dataset$nursery)
dataset$higher=as.factor(dataset$higher)
dataset$internet=as.factor(dataset$internet)
dataset$romantic=as.factor(dataset$romantic)
dataset$Mjob=as.factor(dataset$Mjob)
dataset$Fjob=as.factor(dataset$Fjob)
dataset$reason=as.factor(dataset$reason)
summary(dataset)
dataset[!complete.cases(dataset),]
dataset[duplicated(dataset),]

#dataset=na.omit(dataset)
#dataset=distinct(dataset)

#Visualizing and Exploring Data
library(ggplot2)
ggplot(dataset, aes(x=G) ) + geom_histogram(color = "white",bins = 20)
ggplot(dataset)+geom_bar(aes(G,fill=school))
ggplot(dataset)+geom_bar(aes(G,fill=sex))
ggplot(dataset)+geom_bar(aes(G,fill=address))
ggplot(dataset)+geom_bar(aes(G,fill=famsize))
ggplot(dataset)+geom_bar(aes(G,fill=Pstatus))
ggplot(dataset,aes(x=G,y=Medu))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=Fedu))+geom_line()+geom_smooth()
ggplot(dataset)+geom_bar(aes(G,fill=Mjob))
ggplot(dataset)+geom_bar(aes(G,fill=Fjob))
ggplot(dataset)+geom_bar(aes(G,fill=reason))
ggplot(dataset)+geom_bar(aes(G,fill=guardian))
ggplot(dataset,aes(x=G,y=traveltime))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=studytime))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=failures))+geom_line()+geom_smooth()
ggplot(dataset)+geom_bar(aes(G,fill=schoolsup))
ggplot(dataset)+geom_bar(aes(G,fill=famsup))
ggplot(dataset)+geom_bar(aes(G,fill=paid))
ggplot(dataset)+geom_bar(aes(G,fill=activities))
ggplot(dataset)+geom_bar(aes(G,fill=nursery))
ggplot(dataset)+geom_bar(aes(G,fill=higher))
ggplot(dataset)+geom_bar(aes(G,fill=internet))
ggplot(dataset)+geom_bar(aes(G,fill=romantic))
ggplot(dataset,aes(x=G,y=famrel))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=freetime))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=goout))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=Dalc))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=Walc))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=health))+geom_line()+geom_smooth()
ggplot(dataset,aes(x=G,y=absences))+geom_line()+geom_smooth()
final_dataset=subset(dataset,select = -c(school,address,famsize,Pstatus,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic))
final_dataset
final_dataset[,c('sex','Mjob','Fjob')]=sapply(final_dataset[,c('sex','Mjob','Fjob')], unclass)
final_dataset

#Modelling Data
Model=lm(G~.,data = final_dataset)
cat("Regression model:\n")
summary(Model)
plot(Model)